### PR TITLE
Test hypothesis

### PR DESCRIPTION
**Pull request by gitmarek**

### CODE REVIEW

**Comment by gitmarek** [comment]
Introduce [Hypothesis](https://hypothesis.works) to Supriya's test suite (while learning how to use both...).

Ref.: [280#issuecomment-1317731258](https://github.com/josiah-wolf-oberholtzer/supriya/pull/280#issuecomment-1317731258)

@josiah-wolf-oberholtzer, I would appreciate your ideas and suggestions on how to proceed with this branch.

**Comment by josiah-wolf-oberholtzer** [comment]
Oh, very cool. TBH I've never personally used hypothesis (although I work on projects for my day job that use it effectively), so just working off a hunch that it would be helpful. Excited to see what you come up with here. I suspect the big payoff will be testing node allocation / deletion / movement logic.

**Comment by gitmarek** [comment]
I will focus on [`test_Bus.py`](https://github.com/gitmarek/supriya/blob/test-hypothesis/tests/realtime/test_Bus.py) as a playground for writing tests with Hypothesis.

**Comment by gitmarek** [comment]
I want to preserve the original test cases from `test_Bus.py` and `test_BusGroup.py` and simultaneously expand their scope.  


Here's my approach how to test the interaction of complex objects living on the audio engine with Supriya's state:

1.  Generate two disjoint sets of unique copies of the same object, e.g. Bus objects allocated on the server.  I call one set "control" and the other "test".
2.  Perform some action (e.g. bus set and reset) on the objects from the "test" group.  Assert the desired result.
3.  Assert that the "control" group remains in the default state throughout the test.
  
See one of the original tests: [`test_allocate_04`](https://github.com/josiah-wolf-oberholtzer/supriya/blob/main/tests/realtime/test_Bus.py#L103) from which I took inspiration.

**Comment by gitmarek** [comment]
The implementation of that testing strategy uses `composite()` from `hypothesis.strategies` and a custom decorator `get_control_test_groups()` to quickly turn a strategy-generating function into two lists of copies (*test* and *control*) of the object to be tested.

I found that the best way to pass the strategies into test functions armed with `pytest` fixtures etc., is by packing a "test sample" into a dataclass.  This way, typing annotations help ensure consistency, and unpacking all parameters inside the test function is easy to read.  Also, by using dataclasses, failed test reports stay human-readable.

Thanks to all these tricks, some tests already look quite elegant, e.g. [test_getset()](https://github.com/gitmarek/supriya/blob/201a194cc3c9d462a402df75907de2b1d000589b/tests/proptest/test_Bus.py#L155-L170).

**Pull request closed without merging**
